stack=[]
stack.append("a")
stack.append("b")
stack.append("c")
print("initial stack", stack)
print("elements poped from stack:")
print(stack.pop())
print(stack.pop())
print(stack.pop())
print("stack after elements are popped:", stack)
